FROM codercom/code-server:4.104.0

RUN mkdir -p /home/coder/project && mkdir -p /home/coder/.local && mkdir -p /home/coder/.local/share/code-server/User/workspaceStorage

RUN chmod a+w /home/coder/project/
RUN chmod a+w -R /home/coder/.local
